SELECT_TABLE_PREFIX = """
SELECT SUBSTRING_INDEX(table_name, '_', 1) as prefix 
FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' LIMIT 1;
"""

SELECT_CURRENT_USER_PRIVILEGES = """
SHOW GRANTS FOR CURRENT_USER();
"""